spring:
  application:
    name: sentinel-sample #应用名&微服务id
  cloud:
    sentinel: #Sentinel Dashboard通信地址
      transport:
        dashboard: localhost:9200
      eager: true #取消控制台懒加载
    nacos: #Nacos通信地址
      server-addr: localhost:8848,localhost:8849,localhost:8850
      username: nacos
      password: nacos
server:
  port: 9201
management:
  endpoints:
    web: #将所有可用的监控指标项对外暴露
      exposure: #可以访问 /actuator/sentinel进行查看Sentinel监控项
        include: '*'
