server:
  port: 8000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  application:
    name: b-service
logging:
  level:
    root: debug