spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.100.51.65:8848,10.100.51.65:8849,10.100.51.65:8850
        username: nacos
        password: nacos
server:
  port: 8000
#服务提供者的微服务id
warehouse-service:
  ribbon:
    #设置对应的负载均衡类
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  compression:
    request:
      # 开启请求数据的压缩功能
      enabled: true
      # 压缩数据类型
      mime-types: text/xml, application/xml, application/json
      # 数据压缩下限 2048表示传输数据大于2048 才会进行数据压缩(最小压缩值标准)
      min-request-size: 2048
    # 开启响应数据的压缩功能
    response:
      enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
debug: true
