spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848,192.168.1.5:8849,192.168.1.5:8850
        username: nacos
        password: nacos
server:
  port: 8000
dubbo:
  application:
    name: order-service-dubbo
  registry:
    address: nacos://192.168.1.5:8848,nacos://192.168.1.5:8849,nacos://192.168.1.5:8850