spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8849,localhost:8850
        username: nacos
        password: nacos
server:
  port: 8000
dubbo:
  application:
    name: order-service-dubbo
  registry:
    address: nacos://localhost:8848,nacos://localhost:8849,nacos://localhost:8850