spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.100.51.65:8848,10.100.51.65:8849,10.100.51.65:8850
        username: nacos
        password: nacos
server:
  port: 8000
dubbo:
  application:
    name: order-service-dubbo
  registry:
    address: nacos://10.100.51.65:8848,nacos://10.100.51.65:8849,nacos://10.100.51.65:8850