spring:
  application:
    name: video-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8849,localhost:8850 #nacos服务器地址
        username: nacos #用户名密码
        password: nacos
server:
  port: 9003 #端口号